services:

  nginx:
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - app

  app:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
