services:

  nginx:
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - app

  app:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql
      - ./:/app
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
